#!/bin/bash
# Auto-generated by deploy-kit ccw
# SessionStart hook for Claude Code for the Web
# Runs automatically when CCW session starts

# Only run in CCW cloud environment (not locally)
if [ "$CLAUDE_CODE_REMOTE" != "true" ]; then
  echo "ℹ️  Skipping CCW setup (running locally)"
  exit 0
fi

# Don't exit on errors - handle them gracefully
set +e

# Get project directory
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$PWD}"

echo "🔧 Setting up Claude Code for the Web environment..."
echo "📂 Project: $PROJECT_DIR"

# Copy global CLAUDE.md to ~/.claude/CLAUDE.md
if [ -f "$PROJECT_DIR/.claude/global_claude.md" ]; then
  mkdir -p ~/.claude
  cp "$PROJECT_DIR/.claude/global_claude.md" ~/.claude/CLAUDE.md
  echo "✅ Global CLAUDE.md available at ~/.claude/CLAUDE.md"
else
  echo "⚠️  No .claude/global_claude.md found"
fi

# Check for jq (useful for parsing API responses)
if command -v jq &> /dev/null; then
  echo "✅ jq available"
else
  echo "⚠️  jq not available"
fi

# Check environment variables for API access
if [ -n "$GITHUB_TOKEN" ]; then
  echo "✅ GITHUB_TOKEN available for GitHub API"
else
  echo "⚠️  GITHUB_TOKEN not set"
fi

if [ -n "$LINEAR_API_KEY" ]; then
  echo "✅ LINEAR_API_KEY available for Linear API"
else
  echo "⚠️  LINEAR_API_KEY not set"
fi

# Install project dependencies
if [ -f "$PROJECT_DIR/package.json" ]; then
  echo "📦 Installing project dependencies..."
  cd "$PROJECT_DIR" || exit 1

  # Detect and use appropriate package manager
  if [ -f "pnpm-lock.yaml" ]; then
    pnpm install 2>&1 | grep -v "WARN" && echo "✅ Dependencies installed (pnpm)"
  elif [ -f "yarn.lock" ]; then
    yarn install 2>&1 | grep -v "warning" && echo "✅ Dependencies installed (yarn)"
  elif [ -f "bun.lockb" ]; then
    bun install 2>&1 && echo "✅ Dependencies installed (bun)"
  else
    npm install 2>&1 | grep -v "WARN" && echo "✅ Dependencies installed (npm)"
  fi
fi

# Configure npm token if available
if [ -n "$NPM_TOKEN" ] && [ -n "$CLAUDE_ENV_FILE" ]; then
  if echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc 2>/dev/null; then
    echo "NPM_CONFIGURED=true" >> "$CLAUDE_ENV_FILE"
    echo "✅ npm token configured"
  fi
fi

echo ""
echo "✅ CCW environment setup complete!"
echo ""
echo "See .claude/ccw.md for instructions on using APIs with curl"

exit 0
