#!/bin/bash
# Auto-generated by deploy-kit ccw
# SessionStart hook for Claude Code for the Web
# Runs automatically when CCW session starts

# Only run in CCW cloud environment (not locally)
if [ "$CLAUDE_CODE_REMOTE" != "true" ]; then
  echo "ℹ️  Skipping CCW setup (running locally)"
  exit 0
fi

# Don't exit on errors - handle them gracefully
set +e

echo "🔧 Setting up Claude Code for the Web environment..."

# Check for jq (JSON processor)
if ! command -v jq &> /dev/null; then
  echo "⚠️  jq not available (requires root to install)"
else
  echo "✅ jq available"
fi

# Note: We use scripts/gh_helper.sh for GitHub operations (automatic gh/curl fallback)
if [ -n "$GITHUB_TOKEN" ]; then
  echo "✅ GITHUB_TOKEN available for gh_helper.sh"
else
  echo "⚠️  GITHUB_TOKEN not set - GitHub operations may be limited"
fi

# Install MCP servers globally (best effort)
echo "📦 Installing MCP servers..."
MCP_INSTALLED=0
if npm install -g @playwright/mcp 2>/dev/null; then
  MCP_INSTALLED=$((MCP_INSTALLED + 1))
fi
if npm install -g @upstash/context7-mcp 2>/dev/null; then
  MCP_INSTALLED=$((MCP_INSTALLED + 1))
fi
if npm install -g linear-mcp-server 2>/dev/null; then
  MCP_INSTALLED=$((MCP_INSTALLED + 1))
fi
echo "✅ Installed $MCP_INSTALLED/3 MCP servers"

# Generate .mcp.json for MCP server configuration
echo "⚙️  Configuring MCP servers..."
cat > "$CLAUDE_PROJECT_DIR/.mcp.json" <<'MCP_CONFIG'
{
  "mcpServers": {
    "playwright": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@playwright/mcp@latest"]
    },
    "context7": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@upstash/context7-mcp"]
    },
    "linear": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "linear-mcp-server"],
      "env": {
        "LINEAR_API_KEY": "${LINEAR_API_KEY}"
      }
    }
  }
}
MCP_CONFIG

# Configure permissions in .claude/settings.json
echo "⚙️  Configuring Claude Code permissions..."
SETTINGS_FILE="$CLAUDE_PROJECT_DIR/.claude/settings.json"
if [ -f "$SETTINGS_FILE" ]; then
  if command -v jq &> /dev/null; then
    # Add permissions to existing settings using jq
    if jq '.permissions = {"allow": ["Bash"]}' "$SETTINGS_FILE" > "$SETTINGS_FILE.tmp" 2>/dev/null; then
      mv "$SETTINGS_FILE.tmp" "$SETTINGS_FILE"
      echo "✅ Permissions configured"
    else
      rm -f "$SETTINGS_FILE.tmp"
      echo "⚠️  Could not update permissions (jq failed)"
    fi
  else
    echo "⚠️  jq not available, skipping permissions update"
  fi
else
  echo "⚠️  Settings file not found at $SETTINGS_FILE"
fi

# Install project dependencies (package.json if exists)
if [ -f "$CLAUDE_PROJECT_DIR/package.json" ]; then
  echo "📦 Installing project dependencies..."
  cd "$CLAUDE_PROJECT_DIR" || exit 1

  # Detect package manager
  if [ -f "pnpm-lock.yaml" ]; then
    if pnpm install 2>&1 | grep -v "WARN"; then
      echo "✅ Dependencies installed (pnpm)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  elif [ -f "yarn.lock" ]; then
    if yarn install 2>&1 | grep -v "warning"; then
      echo "✅ Dependencies installed (yarn)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  elif [ -f "bun.lockb" ]; then
    if bun install 2>&1; then
      echo "✅ Dependencies installed (bun)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  else
    if npm install 2>&1 | grep -v "WARN"; then
      echo "✅ Dependencies installed (npm)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  fi
fi

# Install Python dependencies if requirements.txt exists
if [ -f "$CLAUDE_PROJECT_DIR/requirements.txt" ]; then
  echo "📦 Installing Python dependencies..."
  if pip install -r "$CLAUDE_PROJECT_DIR/requirements.txt" 2>&1 | tail -1; then
    echo "✅ Python dependencies installed"
  else
    echo "⚠️  Some Python dependencies may have failed to install"
  fi
fi

# Persist environment variables for session (if CLAUDE_ENV_FILE is set)
if [ -n "$CLAUDE_ENV_FILE" ]; then
  # Write npm token to npmrc if NPM_TOKEN is set
  if [ -n "$NPM_TOKEN" ]; then
    if echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc 2>/dev/null; then
      echo "NPM_CONFIGURED=true" >> "$CLAUDE_ENV_FILE"
      echo "✅ npm token configured"
    else
      echo "⚠️  Failed to configure npm token"
    fi
  fi
fi

echo ""
echo "✅ CCW environment setup complete!"
echo ""
echo "Environment status:"
if [ -n "$GITHUB_TOKEN" ]; then
  echo "  ✅ GITHUB_TOKEN configured (gh_helper.sh will use gh CLI or curl)"
else
  echo "  ⚠️  GITHUB_TOKEN not set"
fi
if [ -f "$CLAUDE_PROJECT_DIR/.mcp.json" ]; then
  echo "  ✅ MCP configuration (.mcp.json) generated"
fi
if [ -n "$LINEAR_API_KEY" ]; then
  echo "  ✅ Linear API key detected"
fi
if [ -n "$NPM_TOKEN" ] && [ -f ~/.npmrc ]; then
  echo "  ✅ npm authentication configured"
fi

exit 0
