#!/bin/bash
# Auto-generated by deploy-kit ccw
# SessionStart hook for Claude Code for the Web
# Runs automatically when CCW session starts

# Only run in CCW cloud environment (not locally)
if [ "$CLAUDE_CODE_REMOTE" != "true" ]; then
  echo "ℹ️  Skipping CCW setup (running locally)"
  exit 0
fi

set -e

echo "🔧 Setting up Claude Code for the Web environment..."

# Install jq if needed (JSON processor)
if ! command -v jq &> /dev/null; then
  echo "📦 Installing jq..."
  apt-get update 2>/dev/null && apt-get install -y jq 2>/dev/null || true
fi

# Install GitHub CLI if needed
if ! command -v gh &> /dev/null; then
  echo "📦 Installing GitHub CLI..."
  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg 2>/dev/null | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg 2>/dev/null
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  apt-get update 2>/dev/null && apt-get install -y gh 2>/dev/null || true
fi

# Authenticate GitHub CLI if token available
if [ -n "$GITHUB_TOKEN" ]; then
  echo "$GITHUB_TOKEN" | gh auth login --with-token 2>/dev/null
  echo "✅ GitHub CLI authenticated"
else
  echo "⚠️  GITHUB_TOKEN not set - GitHub operations will fail"
fi

# Install MCP servers globally
echo "📦 Installing MCP servers..."
npm install -g @modelcontextprotocol/server-playwright 2>/dev/null
npm install -g @context7/mcp-server 2>/dev/null
npm install -g @modelcontextprotocol/server-linear 2>/dev/null

# Install project dependencies (package.json if exists)
if [ -f "$CLAUDE_PROJECT_DIR/package.json" ]; then
  echo "📦 Installing project dependencies..."
  cd "$CLAUDE_PROJECT_DIR"

  # Detect package manager
  if [ -f "pnpm-lock.yaml" ]; then
    pnpm install
  elif [ -f "yarn.lock" ]; then
    yarn install
  elif [ -f "bun.lockb" ]; then
    bun install
  else
    npm install
  fi
fi

# Install Python dependencies if requirements.txt exists
if [ -f "$CLAUDE_PROJECT_DIR/requirements.txt" ]; then
  echo "📦 Installing Python dependencies..."
  pip install -r "$CLAUDE_PROJECT_DIR/requirements.txt"
fi

# Persist environment variables for session (if CLAUDE_ENV_FILE is set)
if [ -n "$CLAUDE_ENV_FILE" ]; then
  # Write npm token to npmrc if NPM_TOKEN is set
  if [ -n "$NPM_TOKEN" ]; then
    echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
    echo "NPM_CONFIGURED=true" >> "$CLAUDE_ENV_FILE"
  fi
fi

echo ""
echo "✅ CCW environment ready!"
echo ""
echo "Environment:"
echo "  ✅ MCP servers installed (Playwright, Context7, Linear)"
echo "  ✅ GitHub CLI configured"
if [ -n "$LINEAR_API_KEY" ]; then
  echo "  ✅ Linear API key detected"
fi
if [ -n "$NPM_TOKEN" ]; then
  echo "  ✅ npm token configured"
fi

exit 0
