import fs from 'fs-extra';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';
import { execSync } from 'child_process';

/**
 * Setup Claude Code for the Web (CCW) integration
 * Idempotent - can run multiple times to update
 *
 * Follows official CCW best practices:
 * - Uses .claude/ directory (official location)
 * - Creates .claude/settings.json with SessionStart hooks
 * - Auto-installs dependencies on session start
 * - Uses CLAUDE_CODE_REMOTE detection
 * - Uses @ sourcing pattern in CLAUDE.md
 */
export async function setupCCW(projectRoot: string = process.cwd()): Promise<void> {
  console.log(chalk.bold.cyan('\n🔧 Setting up Claude Code for the Web (CCW)\n'));

  const claudeDir = path.join(projectRoot, '.claude');
  const scriptsDir = path.join(projectRoot, 'scripts');
  const workflowsDir = path.join(claudeDir, 'workflows');

  // 1. Copy global CLAUDE.md to .claude/
  await copyGlobalClaudeMd(claudeDir);

  // 2. Copy Claude commands to .claude/workflows/
  await copyClaudeCommands(workflowsDir);

  // 3. Create SessionStart hook script
  await createSessionStartScript(scriptsDir);

  // 4. Create GitHub helper script
  await createGitHubHelper(scriptsDir);

  // 5. Create .claude/settings.json with hooks
  await createSettingsJson(claudeDir, scriptsDir);

  // 6. Update project CLAUDE.md with @ sourcing
  await updateProjectClaudeMd(projectRoot, claudeDir);

  // 7. Detect and output required tokens
  const requiredTokens = await detectRequiredTokens(projectRoot);
  outputTokenList(requiredTokens);

  // 8. Output CCW usage instructions
  outputUsageInstructions();

  console.log(chalk.green('\n✅ CCW setup complete!\n'));
}

/**
 * Copy ~/.claude/CLAUDE.md to .claude/GLOBAL_CLAUDE.md
 */
async function copyGlobalClaudeMd(claudeDir: string): Promise<void> {
  const globalClaudePath = path.join(os.homedir(), '.claude', 'CLAUDE.md');
  const targetPath = path.join(claudeDir, 'GLOBAL_CLAUDE.md');

  if (!await fs.pathExists(globalClaudePath)) {
    console.log(chalk.yellow('⚠️  ~/.claude/CLAUDE.md not found - skipping global rules'));
    return;
  }

  await fs.ensureDir(claudeDir);
  await fs.copy(globalClaudePath, targetPath);
  console.log(chalk.green('✅ Copied ~/.claude/CLAUDE.md → .claude/GLOBAL_CLAUDE.md'));
}

/**
 * Copy all files from ~/.claude/commands/ to .claude/workflows/
 */
async function copyClaudeCommands(workflowsDir: string): Promise<void> {
  const commandsPath = path.join(os.homedir(), '.claude', 'commands');

  if (!await fs.pathExists(commandsPath)) {
    console.log(chalk.yellow('⚠️  ~/.claude/commands/ not found - skipping command workflows'));
    return;
  }

  await fs.ensureDir(workflowsDir);

  const files = await fs.readdir(commandsPath);
  let copiedCount = 0;

  for (const file of files) {
    if (file.endsWith('.md')) {
      const sourcePath = path.join(commandsPath, file);
      const targetPath = path.join(workflowsDir, file);
      await fs.copy(sourcePath, targetPath);
      copiedCount++;
    }
  }

  console.log(chalk.green(`✅ Copied ${copiedCount} Claude commands → .claude/workflows/`));
}

/**
 * Create scripts/setup_ccw.sh with SessionStart hook logic
 * This runs automatically when CCW session starts
 */
async function createSessionStartScript(scriptsDir: string): Promise<void> {
  await fs.ensureDir(scriptsDir);

  const setupScript = `#!/bin/bash
# Auto-generated by deploy-kit ccw
# SessionStart hook for Claude Code for the Web
# Runs automatically when CCW session starts

# Only run in CCW cloud environment (not locally)
if [ "$CLAUDE_CODE_REMOTE" != "true" ]; then
  echo "ℹ️  Skipping CCW setup (running locally)"
  exit 0
fi

# Don't exit on errors - handle them gracefully
set +e

# Get project directory (use CLAUDE_PROJECT_DIR if set, otherwise use PWD)
PROJECT_DIR="\${CLAUDE_PROJECT_DIR:-$PWD}"

echo "🔧 Setting up Claude Code for the Web environment..."
echo "📂 Project: $PROJECT_DIR"

# Check for jq (JSON processor)
if ! command -v jq &> /dev/null; then
  echo "⚠️  jq not available (requires root to install)"
else
  echo "✅ jq available"
fi

# Note: We use scripts/gh_helper.sh for GitHub operations (automatic gh/curl fallback)
if [ -n "$GITHUB_TOKEN" ]; then
  echo "✅ GITHUB_TOKEN available for gh_helper.sh"
else
  echo "⚠️  GITHUB_TOKEN not set - GitHub operations may be limited"
fi

# Install MCP servers globally (best effort)
echo "📦 Installing MCP servers..."
MCP_INSTALLED=0
if npm install -g @playwright/mcp 2>/dev/null; then
  MCP_INSTALLED=$((MCP_INSTALLED + 1))
fi
if npm install -g @upstash/context7-mcp 2>/dev/null; then
  MCP_INSTALLED=$((MCP_INSTALLED + 1))
fi
if npm install -g linear-mcp-server 2>/dev/null; then
  MCP_INSTALLED=$((MCP_INSTALLED + 1))
fi
echo "✅ Installed $MCP_INSTALLED/3 MCP servers"

# Generate .mcp.json for MCP server configuration
echo "⚙️  Configuring MCP servers..."
cat > "$PROJECT_DIR/.mcp.json" <<'MCP_CONFIG'
{
  "mcpServers": {
    "playwright": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@playwright/mcp@latest"]
    },
    "context7": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "@upstash/context7-mcp"]
    },
    "linear": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "linear-mcp-server"],
      "env": {
        "LINEAR_API_KEY": "\${LINEAR_API_KEY}"
      }
    }
  }
}
MCP_CONFIG

# Register MCP servers in ~/.claude.json
echo "⚙️  Registering MCP servers in Claude Code..."
CLAUDE_CONFIG="$HOME/.claude.json"
if [ -f "$CLAUDE_CONFIG" ] && command -v jq &> /dev/null; then
  # Backup original config
  cp "$CLAUDE_CONFIG" "$CLAUDE_CONFIG.backup" 2>/dev/null

  # Add MCP servers to the project configuration
  jq --arg project_dir "$PROJECT_DIR" \\
     '.projects[$project_dir].mcpServers = {
       "playwright": {
         "type": "stdio",
         "command": "npx",
         "args": ["-y", "@playwright/mcp@latest"]
       },
       "context7": {
         "type": "stdio",
         "command": "npx",
         "args": ["-y", "@upstash/context7-mcp"]
       },
       "linear": {
         "type": "stdio",
         "command": "npx",
         "args": ["-y", "linear-mcp-server"],
         "env": {
           "LINEAR_API_KEY": env.LINEAR_API_KEY
         }
       }
     }' "$CLAUDE_CONFIG" > "$CLAUDE_CONFIG.tmp" 2>/dev/null && mv "$CLAUDE_CONFIG.tmp" "$CLAUDE_CONFIG"

  echo "✅ MCP servers registered in Claude Code for $PROJECT_DIR"
else
  echo "⚠️  Could not register MCP servers (jq or ~/.claude.json not available)"
fi

# Configure permissions in .claude/settings.json
echo "⚙️  Configuring Claude Code permissions..."
SETTINGS_FILE="$PROJECT_DIR/.claude/settings.json"
if [ -f "$SETTINGS_FILE" ]; then
  if command -v jq &> /dev/null; then
    # Add permissions to existing settings using jq
    if jq '.permissions = {"allow": ["Bash"]}' "$SETTINGS_FILE" > "$SETTINGS_FILE.tmp" 2>/dev/null; then
      mv "$SETTINGS_FILE.tmp" "$SETTINGS_FILE"
      echo "✅ Permissions configured"
    else
      rm -f "$SETTINGS_FILE.tmp"
      echo "⚠️  Could not update permissions (jq failed)"
    fi
  else
    echo "⚠️  jq not available, skipping permissions update"
  fi
else
  echo "⚠️  Settings file not found at $SETTINGS_FILE"
fi

# Install project dependencies (package.json if exists)
if [ -f "$PROJECT_DIR/package.json" ]; then
  echo "📦 Installing project dependencies..."
  cd "$PROJECT_DIR" || exit 1

  # Detect package manager
  if [ -f "pnpm-lock.yaml" ]; then
    if pnpm install 2>&1 | grep -v "WARN"; then
      echo "✅ Dependencies installed (pnpm)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  elif [ -f "yarn.lock" ]; then
    if yarn install 2>&1 | grep -v "warning"; then
      echo "✅ Dependencies installed (yarn)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  elif [ -f "bun.lockb" ]; then
    if bun install 2>&1; then
      echo "✅ Dependencies installed (bun)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  else
    if npm install 2>&1 | grep -v "WARN"; then
      echo "✅ Dependencies installed (npm)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  fi
fi

# Install Python dependencies if requirements.txt exists
if [ -f "$PROJECT_DIR/requirements.txt" ]; then
  echo "📦 Installing Python dependencies..."
  if pip install -r "$PROJECT_DIR/requirements.txt" 2>&1 | tail -1; then
    echo "✅ Python dependencies installed"
  else
    echo "⚠️  Some Python dependencies may have failed to install"
  fi
fi

# Persist environment variables for session (if CLAUDE_ENV_FILE is set)
if [ -n "$CLAUDE_ENV_FILE" ]; then
  # Write npm token to npmrc if NPM_TOKEN is set
  if [ -n "$NPM_TOKEN" ]; then
    if echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc 2>/dev/null; then
      echo "NPM_CONFIGURED=true" >> "$CLAUDE_ENV_FILE"
      echo "✅ npm token configured"
    else
      echo "⚠️  Failed to configure npm token"
    fi
  fi
fi

echo ""
echo "✅ CCW environment setup complete!"
echo ""
echo "Environment status:"
if [ -n "$GITHUB_TOKEN" ]; then
  echo "  ✅ GITHUB_TOKEN configured (gh_helper.sh will use gh CLI or curl)"
else
  echo "  ⚠️  GITHUB_TOKEN not set"
fi
if [ -f "$PROJECT_DIR/.mcp.json" ]; then
  echo "  ✅ MCP configuration (.mcp.json) generated"
fi
if [ -f "$HOME/.claude.json" ] && command -v jq &> /dev/null; then
  MCP_COUNT=$(jq --arg project_dir "$PROJECT_DIR" '.projects[$project_dir].mcpServers | length' "$HOME/.claude.json" 2>/dev/null || echo "0")
  if [ "$MCP_COUNT" -gt 0 ]; then
    echo "  ✅ MCP servers registered in Claude Code ($MCP_COUNT servers)"
  else
    echo "  ⚠️  MCP servers not registered (restart session to load)"
  fi
fi
if [ -n "$LINEAR_API_KEY" ]; then
  echo "  ✅ Linear API key detected"
fi
if [ -n "$NPM_TOKEN" ] && [ -f ~/.npmrc ]; then
  echo "  ✅ npm authentication configured"
fi

exit 0
`;

  const setupPath = path.join(scriptsDir, 'setup_ccw.sh');
  await fs.writeFile(setupPath, setupScript);
  await fs.chmod(setupPath, 0o755);

  console.log(chalk.green('✅ Created scripts/setup_ccw.sh (SessionStart hook)'));
}

/**
 * Create scripts/gh_helper.sh - GitHub CLI wrapper with curl fallback
 * Auto-detects gh CLI availability and falls back to GitHub API
 */
async function createGitHubHelper(scriptsDir: string): Promise<void> {
  await fs.ensureDir(scriptsDir);

  const helperScript = await fs.readFile(path.join(__dirname, '../../../scripts/gh_helper.sh'), 'utf-8');

  const helperPath = path.join(scriptsDir, 'gh_helper.sh');
  await fs.writeFile(helperPath, helperScript);
  await fs.chmod(helperPath, 0o755);

  console.log(chalk.green('✅ Created scripts/gh_helper.sh (GitHub CLI wrapper)'));
}

/**
 * Create .claude/settings.json with SessionStart hooks
 * Uses $CLAUDE_PROJECT_DIR for portability
 */
async function createSettingsJson(claudeDir: string, scriptsDir: string): Promise<void> {
  await fs.ensureDir(claudeDir);

  const settings = {
    permissions: {
      allow: ['Bash'],
    },
    hooks: {
      SessionStart: [
        {
          matcher: 'startup',
          hooks: [
            {
              type: 'command',
              command: '"$CLAUDE_PROJECT_DIR/scripts/setup_ccw.sh"',
            },
          ],
        },
      ],
    },
  };

  const settingsPath = path.join(claudeDir, 'settings.json');
  await fs.writeFile(settingsPath, JSON.stringify(settings, null, 2));

  console.log(chalk.green('✅ Created .claude/settings.json (auto-runs setup on session start)'));
}

/**
 * Update project CLAUDE.md with @ sourcing pattern
 * Uses official CCW best practice: @.claude/GLOBAL_CLAUDE.md
 */
async function updateProjectClaudeMd(projectRoot: string, claudeDir: string): Promise<void> {
  const claudeMdPath = path.join(projectRoot, 'CLAUDE.md');

  if (!await fs.pathExists(claudeMdPath)) {
    console.log(chalk.yellow('⚠️  CLAUDE.md not found - skipping update'));
    return;
  }

  let content = await fs.readFile(claudeMdPath, 'utf-8');

  // Check if sourcing already exists
  if (content.includes('@.claude/GLOBAL_CLAUDE.md') || content.includes('.claude/GLOBAL_CLAUDE.md')) {
    console.log(chalk.gray('   CLAUDE.md already sources global rules'));
    return;
  }

  // Add @ sourcing after title (official CCW pattern)
  const lines = content.split('\n');
  const titleIndex = lines.findIndex((line: string) => line.startsWith('#'));

  if (titleIndex !== -1) {
    lines.splice(titleIndex + 1, 0, '',
      '**IMPORTANT:** See your global CLAUDE.md for universal rules that apply to ALL projects.',
      '- **Local users:** Use `~/.claude/CLAUDE.md` (your personal global file)',
      '- **CCW users:** Use `.claude/GLOBAL_CLAUDE.md` (auto-setup by `dk ccw`)',
      ''
    );

    content = lines.join('\n');
    await fs.writeFile(claudeMdPath, content);
    console.log(chalk.green('✅ Updated ./CLAUDE.md with @ sourcing pattern'));
  }
}

/**
 * Update .gitignore
 * Not needed - .claude/settings.json should be committed (contains SessionStart hook config)
 * The setup script modifies it at runtime in CCW to add permissions
 */
async function updateGitignore(projectRoot: string): Promise<void> {
  // No-op - settings.json needs to be in git for SessionStart hook to work
  console.log(chalk.gray('   .claude/settings.json will be committed (contains SessionStart hook)'));
}

/**
 * Detect which tokens are required
 */
async function detectRequiredTokens(projectRoot: string): Promise<string[]> {
  const tokens: string[] = ['GITHUB_TOKEN', 'LINEAR_API_KEY'];

  // Check if npm package (needs NPM_TOKEN)
  const packageJsonPath = path.join(projectRoot, 'package.json');
  if (await fs.pathExists(packageJsonPath)) {
    const packageJson = await fs.readJson(packageJsonPath);
    if (packageJson.publishConfig || packageJson.name?.startsWith('@')) {
      tokens.push('NPM_TOKEN');
    }
  }

  return tokens;
}

/**
 * Output list of required tokens
 */
function outputTokenList(tokens: string[]): void {
  console.log('\nRequired CCW environment variables:');
  console.log(chalk.gray('━'.repeat(60)));

  for (const token of tokens) {
    const hint = getTokenHint(token);
    console.log(`${chalk.cyan(token.padEnd(25))} ${chalk.gray(hint)}`);
  }

  console.log(chalk.gray('━'.repeat(60)));
  console.log(chalk.yellow('\nNote: For deployments, use Desktop Claude Code or GitHub Actions.'));
  console.log(chalk.yellow('      CCW is for feature development, refactoring, and testing only.'));
}

/**
 * Get hint for where to find token
 */
function getTokenHint(token: string): string {
  switch (token) {
    case 'GITHUB_TOKEN':
      return '(gh auth token)';
    case 'LINEAR_API_KEY':
      return '(https://linear.app/settings/api)';
    case 'NPM_TOKEN':
      return '(cat ~/.npmrc | grep _authToken)';
    default:
      return '';
  }
}

/**
 * Output CCW usage instructions
 */
function outputUsageInstructions(): void {
  console.log('\nHow to use CCW:');
  console.log(chalk.gray('━'.repeat(60)));
  console.log(chalk.white(`
1. Go to claude.ai/code
2. Connect your GitHub account
3. Set environment variables in CCW:
   - GITHUB_TOKEN (required)
   - LINEAR_API_KEY (if using Linear)
   - NPM_TOKEN (if publishing packages)

4. Select this repository
5. Start your task - setup runs automatically!

The SessionStart hook will:
  ✅ Auto-install MCP servers (Playwright, Context7, Linear)
  ✅ Auto-authenticate GitHub CLI
  ✅ Auto-install project dependencies
  ✅ Configure npm for publishing

No manual setup needed - just start coding!
`));
  console.log(chalk.gray('━'.repeat(60)));
}
