import fs from 'fs-extra';
import * as path from 'path';
import * as os from 'os';
import chalk from 'chalk';
import { execSync } from 'child_process';

/**
 * Setup Claude Code for the Web (CCW) integration
 * Idempotent - can run multiple times to update
 *
 * Follows official CCW best practices:
 * - Uses .claude/ directory (official location)
 * - Creates .claude/settings.json with SessionStart hooks
 * - Auto-installs dependencies on session start
 * - Uses CLAUDE_CODE_REMOTE detection
 * - Uses @ sourcing pattern in CLAUDE.md
 */
export async function setupCCW(projectRoot: string = process.cwd()): Promise<void> {
  console.log(chalk.bold.cyan('\n🔧 Setting up Claude Code for the Web (CCW)\n'));

  const claudeDir = path.join(projectRoot, '.claude');
  const scriptsDir = path.join(projectRoot, 'scripts');

  // 1. Copy global CLAUDE.md to .claude/
  await copyGlobalClaudeMd(claudeDir);

  // 2. Create SessionStart hook script
  await createSessionStartScript(scriptsDir);

  // 3. Create GitHub helper script
  await createGitHubHelper(scriptsDir);

  // 4. Create .claude/settings.json with hooks
  await createSettingsJson(claudeDir, scriptsDir);

  // 5. Create .mcp.json for MCP server configuration
  await createMcpJson(projectRoot);

  // 6. Update project CLAUDE.md with @ sourcing
  await updateProjectClaudeMd(projectRoot, claudeDir);

  // 7. Detect and output required tokens
  const requiredTokens = await detectRequiredTokens(projectRoot);
  outputTokenList(requiredTokens);

  // 8. Output CCW usage instructions
  outputUsageInstructions();

  console.log(chalk.green('\n✅ CCW setup complete!\n'));
}

/**
 * Copy ~/.claude/CLAUDE.md to .claude/global_claude.md
 * This gets committed to git and copied to ~/.claude/CLAUDE.md on CCW server
 */
async function copyGlobalClaudeMd(claudeDir: string): Promise<void> {
  const globalClaudePath = path.join(os.homedir(), '.claude', 'CLAUDE.md');
  const targetPath = path.join(claudeDir, 'global_claude.md');

  if (!await fs.pathExists(globalClaudePath)) {
    console.log(chalk.yellow('⚠️  ~/.claude/CLAUDE.md not found - skipping global rules'));
    return;
  }

  await fs.ensureDir(claudeDir);
  await fs.copy(globalClaudePath, targetPath);
  console.log(chalk.green('✅ Copied ~/.claude/CLAUDE.md → .claude/global_claude.md'));
}

/**
 * Create scripts/setup_ccw.sh with SessionStart hook logic
 * This runs automatically when CCW session starts
 */
async function createSessionStartScript(scriptsDir: string): Promise<void> {
  await fs.ensureDir(scriptsDir);

  const setupScript = `#!/bin/bash
# Auto-generated by deploy-kit ccw
# SessionStart hook for Claude Code for the Web
# Runs automatically when CCW session starts

# Only run in CCW cloud environment (not locally)
if [ "$CLAUDE_CODE_REMOTE" != "true" ]; then
  echo "ℹ️  Skipping CCW setup (running locally)"
  exit 0
fi

# Don't exit on errors - handle them gracefully
set +e

# Get project directory (use CLAUDE_PROJECT_DIR if set, otherwise use PWD)
PROJECT_DIR="\${CLAUDE_PROJECT_DIR:-$PWD}"

echo "🔧 Setting up Claude Code for the Web environment..."
echo "📂 Project: $PROJECT_DIR"

# Copy global CLAUDE.md to ~/.claude/CLAUDE.md
if [ -f "$PROJECT_DIR/.claude/global_claude.md" ]; then
  mkdir -p ~/.claude
  cp "$PROJECT_DIR/.claude/global_claude.md" ~/.claude/CLAUDE.md
  echo "✅ Global CLAUDE.md copied to ~/.claude/CLAUDE.md"
else
  echo "⚠️  No .claude/global_claude.md found (run 'dk ccw' locally to create)"
fi

# Check for jq (JSON processor)
if ! command -v jq &> /dev/null; then
  echo "⚠️  jq not available (requires root to install)"
else
  echo "✅ jq available"
fi

# Note: We use scripts/gh_helper.sh for GitHub operations (automatic gh/curl fallback)
if [ -n "$GITHUB_TOKEN" ]; then
  echo "✅ GITHUB_TOKEN available for gh_helper.sh"
else
  echo "⚠️  GITHUB_TOKEN not set - GitHub operations may be limited"
fi

# Install MCP servers globally (best effort)
echo "📦 Installing MCP servers..."
MCP_INSTALLED=0
if npm install -g @playwright/mcp 2>/dev/null; then
  MCP_INSTALLED=$((MCP_INSTALLED + 1))
fi
if npm install -g @upstash/context7-mcp 2>/dev/null; then
  MCP_INSTALLED=$((MCP_INSTALLED + 1))
fi
if npm install -g linear-mcp-server 2>/dev/null; then
  MCP_INSTALLED=$((MCP_INSTALLED + 1))
fi
echo "✅ Installed $MCP_INSTALLED/3 MCP servers"

# Verify .mcp.json exists (should be committed to git)
if [ -f "$PROJECT_DIR/.mcp.json" ]; then
  echo "✅ MCP configuration (.mcp.json) found"
else
  echo "⚠️  .mcp.json not found - MCP servers may not be available"
fi

# Note: MCP servers are auto-discovered from .mcp.json (committed to git)
# No need to modify ~/.claude.json - it happens too late in SessionStart hook

# Configure permissions in .claude/settings.json
echo "⚙️  Configuring Claude Code permissions..."
SETTINGS_FILE="$PROJECT_DIR/.claude/settings.json"
if [ -f "$SETTINGS_FILE" ]; then
  if command -v jq &> /dev/null; then
    # Add permissions to existing settings using jq
    if jq '.permissions = {"allow": ["Bash"]}' "$SETTINGS_FILE" > "$SETTINGS_FILE.tmp" 2>/dev/null; then
      mv "$SETTINGS_FILE.tmp" "$SETTINGS_FILE"
      echo "✅ Permissions configured"
    else
      rm -f "$SETTINGS_FILE.tmp"
      echo "⚠️  Could not update permissions (jq failed)"
    fi
  else
    echo "⚠️  jq not available, skipping permissions update"
  fi
else
  echo "⚠️  Settings file not found at $SETTINGS_FILE"
fi

# Install project dependencies (package.json if exists)
if [ -f "$PROJECT_DIR/package.json" ]; then
  echo "📦 Installing project dependencies..."
  cd "$PROJECT_DIR" || exit 1

  # Detect package manager
  if [ -f "pnpm-lock.yaml" ]; then
    if pnpm install 2>&1 | grep -v "WARN"; then
      echo "✅ Dependencies installed (pnpm)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  elif [ -f "yarn.lock" ]; then
    if yarn install 2>&1 | grep -v "warning"; then
      echo "✅ Dependencies installed (yarn)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  elif [ -f "bun.lockb" ]; then
    if bun install 2>&1; then
      echo "✅ Dependencies installed (bun)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  else
    if npm install 2>&1 | grep -v "WARN"; then
      echo "✅ Dependencies installed (npm)"
    else
      echo "⚠️  Some dependencies may have failed to install"
    fi
  fi
fi

# Install Python dependencies if requirements.txt exists
if [ -f "$PROJECT_DIR/requirements.txt" ]; then
  echo "📦 Installing Python dependencies..."
  if pip install -r "$PROJECT_DIR/requirements.txt" 2>&1 | tail -1; then
    echo "✅ Python dependencies installed"
  else
    echo "⚠️  Some Python dependencies may have failed to install"
  fi
fi

# Persist environment variables for session (if CLAUDE_ENV_FILE is set)
if [ -n "$CLAUDE_ENV_FILE" ]; then
  # Write npm token to npmrc if NPM_TOKEN is set
  if [ -n "$NPM_TOKEN" ]; then
    if echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc 2>/dev/null; then
      echo "NPM_CONFIGURED=true" >> "$CLAUDE_ENV_FILE"
      echo "✅ npm token configured"
    else
      echo "⚠️  Failed to configure npm token"
    fi
  fi
fi

echo ""
echo "✅ CCW environment setup complete!"
echo ""
echo "Environment status:"
if [ -f ~/.claude/CLAUDE.md ]; then
  echo "  ✅ Global CLAUDE.md available at ~/.claude/CLAUDE.md"
fi
if [ -n "$GITHUB_TOKEN" ]; then
  echo "  ✅ GITHUB_TOKEN configured (gh_helper.sh will use gh CLI or curl)"
else
  echo "  ⚠️  GITHUB_TOKEN not set"
fi
if [ -f "$PROJECT_DIR/.mcp.json" ]; then
  echo "  ✅ MCP configuration (.mcp.json) available"
  echo "  ℹ️  MCP servers auto-loaded from .mcp.json at session start"
fi
if [ -n "$LINEAR_API_KEY" ]; then
  echo "  ✅ Linear API key detected"
fi
if [ -n "$NPM_TOKEN" ] && [ -f ~/.npmrc ]; then
  echo "  ✅ npm authentication configured"
fi

exit 0
`;

  const setupPath = path.join(scriptsDir, 'setup_ccw.sh');
  await fs.writeFile(setupPath, setupScript);
  await fs.chmod(setupPath, 0o755);

  console.log(chalk.green('✅ Created scripts/setup_ccw.sh (SessionStart hook)'));
}

/**
 * Create scripts/gh_helper.sh - GitHub CLI wrapper with curl fallback
 * Auto-detects gh CLI availability and falls back to GitHub API
 */
async function createGitHubHelper(scriptsDir: string): Promise<void> {
  await fs.ensureDir(scriptsDir);

  const helperScript = await fs.readFile(path.join(__dirname, '../../../scripts/gh_helper.sh'), 'utf-8');

  const helperPath = path.join(scriptsDir, 'gh_helper.sh');
  await fs.writeFile(helperPath, helperScript);
  await fs.chmod(helperPath, 0o755);

  console.log(chalk.green('✅ Created scripts/gh_helper.sh (GitHub CLI wrapper)'));
}

/**
 * Create .claude/settings.json with SessionStart hooks
 * Uses $CLAUDE_PROJECT_DIR for portability
 */
async function createSettingsJson(claudeDir: string, scriptsDir: string): Promise<void> {
  await fs.ensureDir(claudeDir);

  const settings = {
    permissions: {
      allow: ['Bash'],
    },
    hooks: {
      SessionStart: [
        {
          matcher: 'startup',
          hooks: [
            {
              type: 'command',
              command: '"$CLAUDE_PROJECT_DIR/scripts/setup_ccw.sh"',
            },
          ],
        },
      ],
    },
  };

  const settingsPath = path.join(claudeDir, 'settings.json');
  await fs.writeFile(settingsPath, JSON.stringify(settings, null, 2));

  console.log(chalk.green('✅ Created .claude/settings.json (auto-runs setup on session start)'));
}

/**
 * Update project CLAUDE.md with CCW info (optional)
 * No longer adds sourcing pattern - global rules are copied to ~/.claude/CLAUDE.md on CCW server
 */
async function updateProjectClaudeMd(projectRoot: string, claudeDir: string): Promise<void> {
  const claudeMdPath = path.join(projectRoot, 'CLAUDE.md');

  if (!await fs.pathExists(claudeMdPath)) {
    console.log(chalk.yellow('⚠️  CLAUDE.md not found - skipping update'));
    return;
  }

  // No changes needed - project CLAUDE.md stays clean with only project-specific instructions
  // Global rules are handled by copying .claude/global_claude.md → ~/.claude/CLAUDE.md on CCW server
  console.log(chalk.gray('   CLAUDE.md remains project-specific (global rules handled by CCW setup)'));
}

/**
 * Update .gitignore
 * Not needed - .claude/settings.json should be committed (contains SessionStart hook config)
 * The setup script modifies it at runtime in CCW to add permissions
 */
async function updateGitignore(projectRoot: string): Promise<void> {
  // No-op - settings.json needs to be in git for SessionStart hook to work
  console.log(chalk.gray('   .claude/settings.json will be committed (contains SessionStart hook)'));
}

/**
 * Create .mcp.json for MCP server configuration
 * This file is copied to ~/.claude.json by SessionStart hook
 * MCP servers will be available in the next CCW session after first setup
 */
async function createMcpJson(projectRoot: string): Promise<void> {
  const mcpJsonPath = path.join(projectRoot, '.mcp.json');

  const mcpConfig = {
    mcpServers: {
      playwright: {
        type: 'stdio',
        command: 'npx',
        args: ['-y', '@playwright/mcp@latest'],
      },
      context7: {
        type: 'stdio',
        command: 'npx',
        args: ['-y', '@upstash/context7-mcp'],
      },
      linear: {
        type: 'stdio',
        command: 'npx',
        args: ['-y', 'linear-mcp-server'],
        env: {
          LINEAR_API_KEY: '${LINEAR_API_KEY}',
        },
      },
    },
  };

  await fs.writeFile(mcpJsonPath, JSON.stringify(mcpConfig, null, 2) + '\n');
  console.log(chalk.green('✅ Created .mcp.json (copied to ~/.claude.json on session start)'));
}

/**
 * Detect which tokens are required
 */
async function detectRequiredTokens(projectRoot: string): Promise<string[]> {
  const tokens: string[] = ['GITHUB_TOKEN', 'LINEAR_API_KEY'];

  // Check if npm package (needs NPM_TOKEN)
  const packageJsonPath = path.join(projectRoot, 'package.json');
  if (await fs.pathExists(packageJsonPath)) {
    const packageJson = await fs.readJson(packageJsonPath);
    if (packageJson.publishConfig || packageJson.name?.startsWith('@')) {
      tokens.push('NPM_TOKEN');
    }
  }

  return tokens;
}

/**
 * Output list of required tokens
 */
function outputTokenList(tokens: string[]): void {
  console.log('\nRequired CCW environment variables:');
  console.log(chalk.gray('━'.repeat(60)));

  for (const token of tokens) {
    const hint = getTokenHint(token);
    console.log(`${chalk.cyan(token.padEnd(25))} ${chalk.gray(hint)}`);
  }

  console.log(chalk.gray('━'.repeat(60)));
  console.log(chalk.yellow('\nNote: For deployments, use Desktop Claude Code or GitHub Actions.'));
  console.log(chalk.yellow('      CCW is for feature development, refactoring, and testing only.'));
}

/**
 * Get hint for where to find token
 */
function getTokenHint(token: string): string {
  switch (token) {
    case 'GITHUB_TOKEN':
      return '(gh auth token)';
    case 'LINEAR_API_KEY':
      return '(https://linear.app/settings/api)';
    case 'NPM_TOKEN':
      return '(cat ~/.npmrc | grep _authToken)';
    default:
      return '';
  }
}

/**
 * Output CCW usage instructions
 */
function outputUsageInstructions(): void {
  console.log('\nHow to use CCW:');
  console.log(chalk.gray('━'.repeat(60)));
  console.log(chalk.white(`
1. Go to claude.ai/code
2. Connect your GitHub account
3. Set environment variables in CCW:
   - GITHUB_TOKEN (required)
   - LINEAR_API_KEY (if using Linear)
   - NPM_TOKEN (if publishing packages)

4. Select this repository
5. Start your task - setup runs automatically!

6. IMPORTANT: After first session, start a NEW session for MCP tools
   MCP servers are loaded at session start, so they won't be available
   in your first session. Just start a new task/session to get:
     ✅ Playwright - Browser automation
     ✅ Context7 - Library documentation
     ✅ Linear - Issue tracking

The SessionStart hook will:
  ✅ Copy global CLAUDE.md to ~/.claude/CLAUDE.md
  ✅ Install MCP server packages (Playwright, Context7, Linear)
  ✅ Configure MCP servers in ~/.claude.json
  ✅ Auto-install project dependencies
  ✅ Configure npm for publishing

After first setup, all features work automatically!
`));
  console.log(chalk.gray('━'.repeat(60)));
}
